### ISSUE TITLE
ImportError: cannot import name 'config'

### ISSUE THREAD

**Issue by linshidewan** [Shiny-Project/Shiny-Spider#1]
最再启动Mirai时，请问这是什么情况?

root@w:~/Mirai# python3 Main.py ignite
Traceback (most recent call last):
  File "Main.py", line 3, in <module>
    import core.database as database
  File "/root/Mirai/core/database.py", line 6, in <module>
    import core.config as config

**Comment by linshidewan** [comment]
ImportError: No module named 'core.config'

**Comment by Last-Order** [comment]
呃，居然真有人去尝试运行了。
这里有个配置文件。请在`core`目录下新建`config.py`文件。
参考写法：

```
DATABASE_NAME = "mirai"
DATABASE_USER = "root"
DATABASE_PASSWORD = ""
SOCKET_HOST = 'Mika的Host'
SOCKET_PORT = 3737
API_KEY = 'Shiny API KEY'
API_SECRET_KEY = 'Shiny API SECRET KEY'
YOUTUBE_API_KEY = 'YOUTUBE API KEY'
YAHOO_API_KEY = 'YAHOO API KEY'

GRAYLOG_API = ''
DISABLE_LOG_REPORT = True
ENABLE_DATABASE_CONSOLE = False

if __name__ == "__main__":
    print(u'请按照文档修改配置文件')

```

因为这个项目一直是自己用的，所以也没写文档，估计您想要把整套跑起来的难度比较大……

**Comment by linshidewan** [comment]
谢谢您的解答
